### ISSUE TITLE
Jackrabbit unable to find repository `/` after sudden deletion of system or redeployment

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-jackrabbit#15]
Standalone issue:

Main issue that appears is that webdav client is unable to connect to jackrabbit with error `raise RemoteResourceNotFound(remote_path) webdav`. Upon investigation jackrabbit does not seem to be using the password provided  `/etc/gluu/conf/jackrabbit_admin_password`. The output of that password is correct however I also notice that there is no `/etc/gluu/conf/.jackrabbit_admin_password.last` file even though `entry point.py` did run with no errors. Also, in secrets `jcr_last_pw` exists and is equal to the password at `/etc/gluu/conf/jackrabbit_admin_password` just because the password was not changed. When overriding the passwords and setting it to the default `admin` jackrabbit went back into motion. The `Main.java` does not output any errors either.

**Comment by iromli** [comment]
As per `gluufederation/jackrabbit:4.5.0-5`, the issue with loading jackrabbit password has been resolved.
