### ISSUE TITLE
Separate jackrabbit password from admin and anonymous ids

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-jackrabbit#4]
Currently ID = password. We need to to be able to set envs for the admin and anonymous ids and password files for the associated passwords. 

`GLUU_JACKRABBIT_ADMIN_ID_FILE` --> `GLUU_JACKRABBIT_ADMIN_ID`

`GLUU_JACKRABBIT_ANONYMOUS_ID_FILE` --> `GLUU_JACKRABBIT_ANONYMOUS_ID`

For passwords:

`GLUU_JACKRABBIT_ANONYMOUS_PASSWORD_FILE` 

`GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE`

We can have a randomly strong generated password for the above and outputted to our gluu secret

**Comment by iromli** [comment]
Implemented in https://github.com/GluuFederation/docker-jackrabbit/commit/263af6330a91c849b62a3457e1a44ea19d94fc75.

Overview:

- added `GLUU_JACKRABBIT_ADMIN_ID` env var (default to `admin`)
- added `GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE` env var (default to `/etc/gluu/conf/jackrabbit_admin_password`)

Those 2 env vars will be propagated in the the following container images:

- `gluufederation/casa`
- `gluufederation/oxauth`
- `gluufederation/oxtrust`
- `gluufederation/oxshibboleth`
- `gluufederation/persistence`

**Comment by moabu** [comment]
🐛 🐛 🐛  

Inside jackrabbit pod:

`GLUU_JACKRABBIT_ADMIN_ID`: `admin`
`GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE`: `/etc/gluu/conf/jackrabbit_admin_password`

```
/ # cat /etc/gluu/conf/jackrabbit_admin_password
Test1234#
```

connection using user `admin` pass `Test1234#` did not work. Instead `admin` with pass `admin` worked.

**Comment by iromli** [comment]
Can you make sure you're using latest build? I was unable to reproduce the issue.

Here's the equivalent docker  command:

```
docker run \
    --rm \
    --name jcr \
    -e GLUU_JACKRABBIT_ADMIN_ID=admin \
    -e GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/gluu/conf/jackrabbit_admin_password \
    -v $PWD/jackrabbit_admin_password:/etc/gluu/conf/jackrabbit_admin_password \
    gluufederation/jackrabbit:4.2.1_dev
```

Env vars:

```
» docker exec jcr env | grep JACKRABBIT
GLUU_JACKRABBIT_ADMIN_ID=admin
GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/gluu/conf/jackrabbit_admin_password
GLUU_JACKRABBIT_CLUSTER=false
GLUU_JACKRABBIT_POSTGRES_USER=postgres
GLUU_JACKRABBIT_POSTGRES_PASSWORD_FILE=/etc/gluu/conf/postgres_password
GLUU_JACKRABBIT_POSTGRES_HOST=localhost
GLUU_JACKRABBIT_POSTGRES_PORT=5432
GLUU_JACKRABBIT_POSTGRES_DATABASE=jackrabbit
```

The password being used for webdav:

```
» docker exec jcr cat /etc/gluu/conf/jackrabbit_admin_password
Test1234#
```

**Comment by moabu** [comment]
Using latest build. It seems some chars aren't accepted. Try placing password `\\s7&I:` for jackrabbit.

**Comment by iromli** [comment]
Do you use standalone or cluster mode?

**Comment by moabu** [comment]
cluster mode

**Comment by iromli** [comment]
Unable to re-produce the issue in docker setup.

```
» docker exec jackrabbit env | grep JACKRABBIT
GLUU_JACKRABBIT_ADMIN_ID=admin
GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/gluu/conf/jackrabbit_admin_password
GLUU_JACKRABBIT_CLUSTER=true
```
Password:

```
» docker exec jackrabbit cat /etc/gluu/conf/jackrabbit_admin_password
\\s7&I:
```

Can you share the k8s manifest file?

**Comment by moabu** [comment]
latest build 👍 . Tried password `3[L;K;Ex#(n;~{}9||~C-T?E` in cluster mode.
