### ISSUE TITLE
Jackrabbit doesn't sync files from postgres backend without a restart

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-jackrabbit#6]
#### Setup:

A multicluster setup with one central postgres between two or more jackrabbits.

#### Expected behavior: 

An action such as creating a TR in one region that generates files in `/opt/shibboleth`  would by default move to the second cluster since the same postgres is used. This behaviour is expected to move directly without any force restarts. 

#### Actual behavior: 

Jackrabbit pod at the second cluster must be restarted in order to sync in from the central backend. 

The following behavior means that the `push` is working fine but the `pull` from postgres is hindered.

**Comment by iromli** [comment]
@moabu do jackrabbit nodes have same `Cluster id` (have a look at `/opt/jackrabbit/repository.xml`) as shown here?

```
<Cluster id="jackrabbit2">
    <Journal class="org.apache.jackrabbit.core.journal.DatabaseJournal">
    </Journal>
</Cluster>
```

Note that if all nodes use same `id`, the sync is unpredictable (some nodes are missing the files).
Currently the `Cluster id` is resolved from container/pod hostname, so the setup must ensure they have different container/pod hostname.
